config/routes.rb
Rails.application.routes.draw do
    root 'welcome#index'
    get '/artists', to: 'artists#index'
    get '/artists/:id', to: 'artists#show', as: 'artist'
    get '/search', to: 'artists#search'
    get '/albums/new', to: 'albums#new', as: 'new_album_now'



  Rails.application.routes.draw do
        resources :tracks do
          collection do
            get :top_100
            get :random
            get :search
          end
        end
      end


    resources :users, only: [] do
      resources :playlists, only: [:index, :show, :destroy, :create, :new]
    end

    devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }


    # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


    resources :albums, only: [:show, :index] do
      resources :comments, only: [:new, :create, :index, :show, :destroy, :edit, :update]
    end

    resources :comments
    resources :albums
    resources :welcome

    resources :playlists, only: [:create, :show]

    #shallow: true


end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist

  has_many :playlists
  has_many :users, through: :playlists
  has_many :tracks

  has_many :comments


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  validates(:content, { :length => { :minimum => 5 } })
  belongs_to :album
  belongs_to :user
end

app/models/playlist.rb
class Playlist < ApplicationRecord

  validates :album_id, uniqueness: true

 belongs_to :user
 belongs_to :album
 has_one :review

#need a scope that will give me the top 5 most saved albums
#i need to figure out when i save an album to a users playlist how i can count how many each album has been saved to use
#order by DESC to get the top 5 and limit it to 5
# i need to add top_5 to playlists table
#count the amount of albums being saved into the playlist
#check album ID
#
#
# def self.top_5
#   if artist_id
#
# end
#
# SELECT (?,?) from GROUP BY

scope :oldest, -> { order(created_at: :asc)}
scope :newest, -> { order(created_at: :desc)}




end

app/models/review.rb
class Review < ApplicationRecord

    belongs_to :album
    belongs_to :user
    belongs_to :playlists


end

app/models/track.rb
class Track < ApplicationRecord
  has_many :tracks
  has_many :playlists, through: :playlists_tracks

  def self.new_from_spotify_track(spotify_track)
    Track.new(
      spotify_id: spotify_track.id,
      name: spotify_track.name,
      artist: spotify_track.artists[0].name,
      image: spotify_track.album.images[0]["url"],
      duration: spotify_track.duration_ms,
      popularity: spotify_track.popularity,
      preview: spotify_track.preview_url
    )
  end



  def self.create_from_spotify_track(spotify_track)
    track = Track.find_by(
      spotify_id: spotify_track.id)
    if track
      track
    else
      track = self.new_from_spotify_track(spotify_track)
      track.save
      track
  end
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :email, uniqueness: true
  validates :email, :password, presence: true

  # devise :omniauthable, :omniauth_providers => [:github]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :playlists
  has_many :albums, through: :playlists
  has_many :comments, through: :albums


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.uid = auth.uid
    end
  end

end

app/models/welcome.rb
class Welcome < ApplicationRecord

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :authenticate_user!, except: [:show]

  def index

        if params[:artist]
            @album = Album.all.collect do |album|
                if album.artist.name.downcase.include?(params[:artist].downcase)
                    album
                end
            end.compact
        else
            @album = Album.all
        end
        if @album.empty?
         flash.now[:alert] = "Sorry, there are no matches for that artist."
     end
 end

  def new
    @album = Album.new
  end


    def show
      if @album_id = params[:album_id]
        @album = RSpotify::Album.search(params[:album_id]).first
      else
         @album = Album.find(params[:id])
       end
    end

    private

    def album_params
      params.require(:album).permit(:name, :release_date, :number_of_tracks, :images, :external_urls )
    end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_user!, except: [:search, :index, :show]

  def search
  end

  def index
    if !params[:artist_name].empty?
      @artists = RSpotify::Artist.search(params[:artist_name])
    else
      redirect_to root_path
    end
  end

  def show
    @artist = RSpotify::Artist.find(params[:id])
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @artist.albums}
    end
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!, except: [:top_100]

  def index
    @tracks = Track.all
  end

  def show
    @track = Track.find(:id)
      if track.valid?
        redirect_to
      else
        render 'new'
      end
    end


  def top_100
    # byebug
    # https://open.spotify.com/playlist/2kpoUUJ5a4Cw3feTkFJhZ2
    s_tracks = RSpotify::Playlist.find("1276640268","4hOKQuZbraPDIfaGbM3lKI").tracks
    @tracks = s_tracks.map do |s_track|
     Track.new_from_spotify_track(s_track)
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController



  def home
        s_tracks = RSpotify::Playlist.browse_featured.first.tracks
        @albums = s_tracks.map do |s_track|
          Track.create_from_spotify_track(s_track)
        end
      end

  def index
    @albums = Album.all
  end



  def about; end

  def contact; end


end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/playlist_helper.rb
module PlaylistHelper
end

app/helpers/review_helper.rb
module ReviewHelper

    def rating_star(rating)
        star = ""
        rating.times do
            star << "<span class='glyphicon glyphicon-star'></span>"
        end
        star.html_safe
    end

    def blank_star(rating)
        blank = 10 - rating
        blank_star = ""
        blank.times do
            blank_star << "<span class='glyphicon glyphicon-star-empty'></span>"
        end
        blank_star.html_safe
    end

    def review_created(review)
        review.created_at.strftime("Review created at %A, %d %b %Y %l:%M %p")
    end

end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/track_helper.rb
module TrackHelper


end

app/helpers/users_helper.rb
module UsersHelper

def user_array
  user_search_allowed = [:artist_name, :spotify_id]
end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_album.html.erb
<h1 style="text-align: center;"><%= @album.artist.name %></h1>
<img src="<%= @album.images %>" height=500 style="padding-left: 36%;">
<h2 style="text-align: center;"><%= @album.name %></h2>
<h4 style="text-align: center;"><%= @album.copyrights %></h4>
<ul class="list-group list-group-flush">
    <% @album.tracks.each do |track| %>
        <li style="text-align: center;" class="list-group-item"><%= track.name %> </li>
    <% end %>
</ul>
<% if current_user %>
<%= link_to "Listen to the Album on Spotify", @album.external_urls %><br><br>

<%= render 'comments/comment' %>
<% end %>

app/views/albums/show.html.erb
<% if @album_id %>
<ul>
  <% @album.artists.each do |artist|%>
  <li style="text-align: center;"><%= artist.name%></li>
  <% end %>
</ul>
<img src="<%= @album.images.first['url'] %>" height=500 style="padding-left: 38%;" >
<h2 style="text-align: center;><%= @album.name %></h2>
<h4 style="text-align: center;><%= @album.label %></h4>
<ul class="list-group list-group-flush">
    <% @album.tracks.each do |track| %>
        <li style="text-align: center; class="list-group-item"><%= track.name %> </li>
    <% end %>
    <% if current_user %>
    <% if flash[:error] != nil %>
        <div class="container-c alert alert-danger" role="alert">
          <%= flash[:error] %>
        </div>
    <% end %>
    <%= form_tag({controller: "playlists", action: "create", method: "post"}) do %>
    <%= hidden_field_tag "album_id", @album.id %>
    <%= submit_tag("Add To Collection", id: "button", class: "btn-lg", name: "Submit") %>
  <% end %>
  <% end %>
</ul>

<% else %>

<%= render partial: 'albums/album' %>

<% end %>

app/views/artists/index.html.erb
<h1 class="page-header">Artists Matching <%= params[:artist_name] %></h1>
<ul class="list-group list-group-flush">
    <% @artists.each do |artist| %>
        <li class="list-group-item"><%= artist.name %> | <%= link_to "Show", artist_path(artist.id) %> </li>
        </ul>
    <% end %>

app/views/artists/search.html.erb
<%= form_tag artists_path, method: "get", html: { class: "form" } do %>
<div class="form-group col-xs-4">
<%= text_field_tag(:artist_name, "", placeholder: "Enter artist name", class: "form-control") %>
</div>
<%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

app/views/artists/show.html.erb
<% if flash[:error] != nil %>
    <div class="container-c alert alert-danger" role="alert">
      <%= flash[:error] %>
    </div>
<% end %>
<h1 class="page-header text-white"><%= @artist.name %></h1>

<div class="row">
  <% @artist.albums(country: 'US').each do |album| %>
    <div class="col-sm-4">
      <h3 class="text-black"><%= album.name %></h3>
      <img src="<%= image_path(album.images.first['url']) %>" height="300">
      <br><br>
      <% if current_user %>
        <%= form_tag({controller: "playlists", action: "create", method: "post"}) do %>
        <%= hidden_field_tag "album_id", album.id %>
        <%= submit_tag("Add To Collection", id: "button", class: "btn-lg", name: "Submit") %>
      <% end %>
    <% end %>
    <br>
    <ul class="list-group list-group-flush">
      <% album.tracks.each do |track| %>
        <li class="list-group-item"><%= track.name %>
        </li>
      <% end %>
    </ul>
  </div>
  <!-- end col-sm-4 -->
<% end %>
</div>
<!--end row-->

app/views/tracks/_form.html.erb
    <% @albums.each do |album| %>
      <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="card-img-top" src="<%= album.image %>" alt="Album Cover">
            <div class="card-body">
              <p class="card-text"><strong><%= album.name %> - <%= album.artist %></strong></p>
              <p class="card-text">
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= form_with url: album_path(album), method: 'get' do |f| %>
                  <%= f.hidden_field :album_id, value: album.id %>
                  <%= f.submit "Go to Album", class: "btn btn-sm btn-outline-secondary"%>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>
  </div>
</div>
</div>
</div>

app/views/tracks/index.html.erb
<h1>Tracks</h1>
<ul>
<% @albums.each do |track|%>
  <li>%= track.name %></li>
</ul>
  <% end %>

app/views/tracks/show.html.erb
<% if current_user %>
<h1 style="text-align: center;"><%= @track.artist.name %></h1>
<img src="<%= @track.images %>" height=500 style="padding-left: 36%;">
<h2 style="text-align: center;"><%= @track.name %></h2>
<h4 style="text-align: center;"><%= @track.copyrights %></h4>
<ul class="list-group list-group-flush">
    <% @track.tracks.each do |track| %>
        <li style="text-align: center;" class="list-group-item"><%= track.name %> </li>
    <% end %>
</ul>

<%= link_to "Listen to the Album on Spotify", @track.external_urls %><br><br>

<%= render 'comments/comment' %>
<% end %>

app/views/tracks/top_100.html.erb
<h1>
  Top 100 !
</h1>
<% @tracks.each do |album| %>
  <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
        <img class="card-img-top" src="<%= album.image %>" alt="Album Cover">
        <div class="card-body">
          <p class="card-text"><strong><%= album.name %></strong></p>
          <p class="card-text">
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/welcome/home.html.erb
<body class="welcome-body">
<% if current_user %>
<%= render 'tracks/form' %>
  <% else %>
    <div class="row">
      <div class="col-md-6">
        <h2>
          Create a Collection</h2>
        <h2>
          Sign in to get started  or you can freely search for your favorite artistbelow.
        </h2>
        <p>
          <a class="btn btn-secondary" href="<%= top_100_tracks_path %>" role="button">See Top 100 Songs! &raquo;</a>
          <a class="btn btn-secondary" href="/search" role="button">Search Database &raquo;</a>
        </p>
      </div>
        </p>
      </div>
      <% @albums.each do |album| %>
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <img class="card-img-top" src="<%= album.image.first %>" alt="Album Cover">
              <div class="card-body">
                <p class="card-text"><strong><%= album.name.first %> - <%= album.artist.first %></strong></p>
                <p class="card-text">
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <%= form_with url: album_path(album), method: 'get' do |f| %>
                    <%= f.hidden_field :album_id, value: album.id %>
                    <%= f.submit "Go to Album", class: "btn btn-sm btn-outline-secondary"%>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
    </div>
  </div>
  </div>
  </div>

  <% end %>
  </body>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h2>
      Create a Collection</h2>
    <h2>
      Sign in to get started  or you can freely search for your favorite artist below.
    </h2>
    <p>
      <a class="btn btn-secondary" href="<%= top_100_tracks_path %>" role="button">See Top 100 Songs! &raquo;</a>
      <a class="btn btn-secondary" href="/search" role="button">Search Database &raquo;</a>
    </p>
  </div>
    </p>
  </div>

<% @albums.each do |album| %>
  <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
        <img class="card-img-top" src="<%= album.images %>" alt="Album Cover">
        <div class="card-body">
          <p class="card-text"><strong><%= album.name %> - <%= album.artist.name%></strong></p>
          <p class="card-text">
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <%= link_to "Go to album", album_path(album), class: "btn btn-sm btn-outline-secondary" %>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>