config/routes.rb
Rails.application.routes.draw do
    root 'welcome#index'
    get '/artists', to: 'artists#index'
    get '/artists/:id', to: 'artists#show', as: 'artist'
    get '/search', to: 'artists#search'
    get '/albums/new', to: 'albums#new', as: 'new_album_now'



  Rails.application.routes.draw do
        resources :tracks do
          collection do
            get :top_100
            get :random
            get :search
          end
        end
      end


    resources :users, only: [] do
      resources :playlists, only: [:index, :show, :destroy, :create, :new]
    end

    devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }


    # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


    resources :albums, only: [:show, :index] do
      resources :comments, only: [:new, :create, :index, :show, :destroy, :edit, :update]
    end

    resources :comments
    resources :albums
    resources :welcome

    resources :playlists, only: [:create, :show]

    #shallow: true


end

app/models/playlist.rb
class Playlist < ApplicationRecord

  validates :album_id, uniqueness: true

 belongs_to :user
 belongs_to :album
 has_one :review

#need a scope that will give me the top 5 most saved albums
#i need to figure out when i save an album to a users playlist how i can count how many each album has been saved to use
#order by DESC to get the top 5 and limit it to 5
# i need to add top_5 to playlists table
#count the amount of albums being saved into the playlist
#check album ID
#
#
# def self.top_5
#   if artist_id
#
# end
#
# SELECT (?,?) from GROUP BY

scope :oldest, -> { order(created_at: :asc)}
scope :newest, -> { order(created_at: :desc)}




end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :authenticate_user!

  def create
    @spotify_album = RSpotify::Album.find(params[:album_id])
    if @spotify_album
      @artist = Artist.find_or_create_by(name: @spotify_album.artists.first.name,
                                         genre: @spotify_album.artists.first.genres[0], images: @spotify_album.artists.first.images[0]['url'])
      @album = Album.find_or_create_by(name: @spotify_album.name, release_date: @spotify_album.release_date,
                                       number_of_tracks: @spotify_album.total_tracks, images: @spotify_album.images[0]['url'], artist: @artist, copyrights: @spotify_album.copyrights.first['text'], external_urls: @spotify_album.external_urls['spotify'])

      if @album.tracks.empty?
        @spotify_album.tracks.each do |track|
          @album.tracks.build(name: track.name, duration_ms: track.duration_ms, explicit: track.explicit,
                              track_number: track.track_number).save
        end
      end
      if current_user.playlists.build(album: @album, rating: 0, name: 'Playlist Name').save
      redirect_to user_playlists_path(current_user)
      else
        flash[:error] = 'Album Already Added to Playlist'
        redirect_to user_playlists_path(current_user)
      end
    end
  end

  def index
    if params[:user_id] = current_user.id
          user_playlists = User.find(params[:user_id]).playlists
          if params[:filter] == "Newest Additions"
                @playlists = user_playlists.newest
              elsif params[:filter] == "Oldest Additions"
                @playlists = user_playlists.oldest
            else
            @playlists = User.find(params[:user_id]).playlists
          end
        else
          redirect_to user_playlists_path(current_user.id)
       end
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy if current_user.playlists.include?(@playlist)
    redirect_to user_playlists_path(current_user.id)
  end

end

app/helpers/playlist_helper.rb
module PlaylistHelper
end

app/views/playlists/index.html.erb
<% if flash[:error] != nil %>
    <div class="container-c alert alert-danger" role="alert">
      <%= flash[:error] %>
    </div>
<% end %>
<%= form_tag "", method: "get" do %>
       <%= select_tag "filter", "<option>Newest Additions</option><option>Oldest Additions</option>".html_safe %>
       <%= submit_tag "Filter" %>
     <% end %>
<div class="album py-5 bg-light">
  <div class="container-fluid">
    <div>
    </div><br>
    <div class="row">
      <% @playlists.each do |playlist| %>
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <img class="card-img-top" src="<%= playlist.album.images %>" alt="Album Cover">
              <div class="card-body">
                <p class="card-text"><strong><%= playlist.album.name %> - <%= playlist.album.artist.name %></strong></p>
                <p class="card-text">
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <a class="btn btn-sm btn-outline-secondary" href="<%= new_album_comment_path(playlist.album) %>">
                        Add Comment
                      </a>
                    <a class="btn btn-sm btn-outline-secondary" href="<%= album_path(playlist.album) %>">
                        Go to Album
                    </a>
                      <%= button_to "Delete", [playlist.user, playlist], method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-outline-secondary" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>