config/routes.rb
Rails.application.routes.draw do
    root 'welcome#index'
    get '/artists', to: 'artists#index'
    get '/artists/:id', to: 'artists#show', as: 'artist'
    get '/search', to: 'artists#search'
    get '/albums/new', to: 'albums#new', as: 'new_album_now'



  Rails.application.routes.draw do
        resources :tracks do
          collection do
            get :top_100
            get :random
            get :search
          end
        end
      end


    resources :users, only: [] do
      resources :playlists, only: [:index, :show, :destroy, :create, :new]
    end

    devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }


    # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


    resources :albums, only: [:show, :index] do
      resources :comments, only: [:new, :create, :index, :show, :destroy, :edit, :update]
    end

    resources :comments
    resources :albums
    resources :welcome

    resources :playlists, only: [:create, :show]

    #shallow: true


end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist

  has_many :playlists
  has_many :users, through: :playlists
  has_many :tracks

  has_many :comments


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  validates(:content, { :length => { :minimum => 5 } })
  belongs_to :album
  belongs_to :user
end

app/models/playlist.rb
class Playlist < ApplicationRecord

  validates :album_id, uniqueness: true

 belongs_to :user
 belongs_to :album
 has_one :review

#need a scope that will give me the top 5 most saved albums
#i need to figure out when i save an album to a users playlist how i can count how many each album has been saved to use
#order by DESC to get the top 5 and limit it to 5
# i need to add top_5 to playlists table
#count the amount of albums being saved into the playlist
#check album ID
#
#
# def self.top_5
#   if artist_id
#
# end
#
# SELECT (?,?) from GROUP BY

scope :oldest, -> { order(created_at: :asc)}
scope :newest, -> { order(created_at: :desc)}




end

app/models/review.rb
class Review < ApplicationRecord

    belongs_to :album
    belongs_to :user
    belongs_to :playlists


end

app/models/track.rb
class Track < ApplicationRecord
  has_many :tracks
  has_many :playlists, through: :playlists_tracks

  def self.new_from_spotify_track(spotify_track)
    Track.new(
      spotify_id: spotify_track.id,
      name: spotify_track.name,
      artist: spotify_track.artists[0].name,
      image: spotify_track.album.images[0]["url"],
      duration: spotify_track.duration_ms,
      popularity: spotify_track.popularity,
      preview: spotify_track.preview_url
    )
  end



  def self.create_from_spotify_track(spotify_track)
    track = Track.find_by(
      spotify_id: spotify_track.id)
    if track
      track
    else
      track = self.new_from_spotify_track(spotify_track)
      track.save
      track
  end
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :email, uniqueness: true
  validates :email, :password, presence: true

  # devise :omniauthable, :omniauth_providers => [:github]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :playlists
  has_many :albums, through: :playlists
  has_many :comments, through: :albums


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.uid = auth.uid
    end
  end

end

app/models/welcome.rb
class Welcome < ApplicationRecord

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :authenticate_user!, except: [:show]

  def index

        if params[:artist]
            @album = Album.all.collect do |album|
                if album.artist.name.downcase.include?(params[:artist].downcase)
                    album
                end
            end.compact
        else
            @album = Album.all
        end
        if @album.empty?
         flash.now[:alert] = "Sorry, there are no matches for that artist."
     end
 end

  def new
    @album = Album.new
  end


    def show
      if @album_id = params[:album_id]
        @album = RSpotify::Album.search(params[:album_id]).first
      else
         @album = Album.find(params[:id])
       end
    end

    private

    def album_params
      params.require(:album).permit(:name, :release_date, :number_of_tracks, :images, :external_urls )
    end
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/playlist_helper.rb
module PlaylistHelper
end

app/helpers/review_helper.rb
module ReviewHelper

    def rating_star(rating)
        star = ""
        rating.times do
            star << "<span class='glyphicon glyphicon-star'></span>"
        end
        star.html_safe
    end

    def blank_star(rating)
        blank = 10 - rating
        blank_star = ""
        blank.times do
            blank_star << "<span class='glyphicon glyphicon-star-empty'></span>"
        end
        blank_star.html_safe
    end

    def review_created(review)
        review.created_at.strftime("Review created at %A, %d %b %Y %l:%M %p")
    end

end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/track_helper.rb
module TrackHelper


end

app/helpers/users_helper.rb
module UsersHelper

def user_array
  user_search_allowed = [:artist_name, :spotify_id]
end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Rails Spotify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <!-- Latest CSS Stylesheet from Bootstrap-->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

   <!-- Latest compiled and minified CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
   <!--===============================================================================================-->
   	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
   <!--===============================================================================================-->
   	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
   <!--===============================================================================================-->
   	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
   <!--===============================================================================================-->
   	<link rel="stylesheet" type="text/css" href="fonts/iconic/css/material-design-iconic-font.min.css">
   <!--===============================================================================================-->
   	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
   <!--===============================================================================================-->
   	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
   <!--===============================================================================================-->
   	<link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
   <!--===============================================================================================-->
   	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
   <!--===============================================================================================-->
   	<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
   <!--===============================================================================================-->
   <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
   	<link rel="stylesheet" type="text/css" href="css/util.css">
   	<link rel="stylesheet" type="text/css" href="css/main.css">
   <!--===============================================================================================-->
  </head>

  <body>
    <% if current_user %>
      <!-- NAVIGATION -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a style="color: #F3CAC3;" class="navbar-brand" href="/">Beats By Bryan</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div style="text-align: right;" class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "Homepage", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "My Playlist Collection", user_playlists_path(current_user), class: "nav-link" %>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="/search">Search</a>
            </li>
            <li class="nav-item">
              <%= form_with url: destroy_user_session_path,class: "form_sign-out", method: :delete do |f| %>
              <%= f.submit "Sign Out", class: "nav-link"%>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
      <!-- flag -->
      <% else %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a style="color: #F3CAC3;" class="navbar-brand" href="/">Beats-By-Bryan</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <%= link_to "Homepage", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
                <span class="sr-only">(current)</span>
            </li>
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </nav>
      <% end %>
      <!-- flag -->

    <div class="">
      <%= yield %>
      <%= render 'layouts/alerts' %>
    </div>

      <!--===============================================================================================-->
      	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
      <!--===============================================================================================-->
      	<script src="vendor/animsition/js/animsition.min.js"></script>
      <!--===============================================================================================-->
      	<script src="vendor/bootstrap/js/popper.js"></script>
      	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
      <!--===============================================================================================-->
      	<script src="vendor/select2/select2.min.js"></script>
      <!--===============================================================================================-->
      	<script src="vendor/daterangepicker/moment.min.js"></script>
      	<script src="vendor/daterangepicker/daterangepicker.js"></script>
      <!--===============================================================================================-->
      	<script src="vendor/countdowntime/countdowntime.js"></script>
      <!--===============================================================================================-->
      	<script src="js/main.js"></script>
        <script src="js/jquery.min.js"></script>
    <script src="js/popper.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/main.js"></script>
  </body>

</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V9</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="css/util.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
<!--===============================================================================================-->
</head>
<body>
  <%= yield %>




  <!--===============================================================================================-->
  	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
  <!--===============================================================================================-->
  	<script src="vendor/animsition/js/animsition.min.js"></script>
  <!--===============================================================================================-->
  	<script src="vendor/bootstrap/js/popper.js"></script>
  	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
  <!--===============================================================================================-->
  	<script src="vendor/select2/select2.min.js"></script>
  <!--===============================================================================================-->
  	<script src="vendor/daterangepicker/moment.min.js"></script>
  	<script src="vendor/daterangepicker/daterangepicker.js"></script>
  <!--===============================================================================================-->
  	<script src="vendor/countdowntime/countdowntime.js"></script>
  <!--===============================================================================================-->
  	<script src="js/main.js"></script>
  </body>
  </html>